// Movie Production Routes tested with REST Client extension
### Get all movies
GET https://team-interests.onrender.com/movies
Accept: application/json

### Get a movie by ID
GET https://team-interests.onrender.com/movies/68dddcaa4dda3d6e3d19ba34
Accept: application/json

### Create a new movie
POST https://team-interests.onrender.com/movies
Content-Type: application/json

{
  "title": "Test",
  "director": "TBD",
  "language": "English",
  "year": 2024,
  "genre": ["drama"],
  "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
}

### Update a movie by ID
PUT https://team-interests.onrender.com/movies/68dddcaa4dda3d6e3d19ba34
Content-Type: application/json

{
  "title": "Test Updated",
  "director": "TBD",
  "language": "English",
  "year": 2024,
  "genre": ["drama"],
  "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
}

### Delete a movie by ID
DELETE https://team-interests.onrender.com/movies/68dddcaa4dda3d6e3d19ba34