// Movie Routes locally tested with REST Client extension
### Get all movies
GET http://localhost:3003/movies
Accept: application/json

### Get a movie by ID
GET http://localhost:3003/movies/68e034d4d6e6e300e74440ac
Accept: application/json

### Create a new movie
POST http://localhost:3003/movies
Content-Type: application/json

{
  "title": "Test",
  "director": "TBD",
  "language": "English",
  "year": 2024,
  "genre": ["drama"],
  "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
}

### Update a movie by ID
PUT http://localhost:3003/movies/68e07134afa0ca0d0a5a99f7
Content-Type: application/json

{
  "title": "Test Updated",
  "director": "TBD",
  "language": "English",
  "year": 2024,
  "genre": ["drama"],
  "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
}

### Delete a movie by ID
DELETE http://localhost:3003/movies/68e065e8a2071313d5acd46f